// <auto-generated />
using System;
using BinZone.Sample.EF.MultiDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MultiDbWithEFCore.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20180819111451_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BinZone.Sample.EF.MultiDB.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("NickName");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = new Guid("00ec036f-ae0e-423e-b55c-49405f36accd"), Created = new DateTime(2018, 8, 19, 11, 14, 51, 225, DateTimeKind.Utc), NickName = "Example", Password = "your_password", Username = "sample@example.com" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
